name: zig-code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    name: Check if zig code compiles and runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup zig
        uses: mlugg/setup-zig@v1
      - name: Setup just
        uses: extractions/setup-just@v2
      - name: Compile and run zig code
        run: just z-run
